/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 보고서 조회 API
         * @description 날짜별 보고서 조회. 날짜 미입력 시 오늘 날짜 조회
         */
        get: operations["getReport"];
        put?: never;
        /**
         * 보고서 생성 API
         * @description 지정 날짜의 급식/급수 로그를 GPT로 분석해 보고서를 생성합니다. 날짜 미입력 시 오늘 날짜로 생성됩니다.
         */
        post: operations["generateReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파일 업로드
         * @description 라즈베리파이에서 녹화/캡처 파일을 업로드합니다.
         */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 API */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 액세스 토큰 재발급 API
         * @description 쿠키에 저장된 리프레시 토큰을 사용하여 새로운 액세스 토큰을 발급받습니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/mail/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 인증번호 확인 */
        post: operations["checkCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/mail/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증번호 발송 */
        post: operations["sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃 API
         * @description 쿠키에 저장된 리프레시 토큰을 무효화합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 API */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/watering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 급수 로그 기록 API
         * @description 라즈베리파이에서 급수 후 로그를 저장합니다.
         */
        post: operations["createWateringLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/feeding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 급식 로그 기록 API
         * @description 라즈베리파이에서 급식 후 로그를 저장합니다.
         */
        post: operations["createFeedingLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispensers/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 급식 스케줄 등록 API */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/memo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 메모 수정 API */
        patch: operations["updateMemo"];
        trace?: never;
    };
    "/api/v1/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 반려동물 조회 API */
        get: operations["getMyPet"];
        put?: never;
        post?: never;
        /** 반려동물 삭제 API */
        delete: operations["deletePet"];
        options?: never;
        head?: never;
        /** 반려동물 정보 수정 API */
        patch: operations["updatePet"];
        trace?: never;
    };
    "/api/v1/dispensers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 디스펜서 조회 API */
        get: operations["getMyDispenser"];
        put?: never;
        post?: never;
        /** 디스펜서 연결 해제 API */
        delete: operations["deleteDispenser"];
        options?: never;
        head?: never;
        /** 디스펜서 설정 수정 API */
        patch: operations["updateDispenser"];
        trace?: never;
    };
    "/api/v1/dispensers/schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 급식 스케줄 삭제 API */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        /** 급식 스케줄 수정 API */
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 카메라 조회 API */
        get: operations["getMyCamera"];
        put?: never;
        post?: never;
        /** 카메라 연결 해제 API */
        delete: operations["deleteCamera"];
        options?: never;
        head?: never;
        /**
         * 카메라 설정 수정 API
         * @description 디바이스명, 야간모드, 프라이빗 모드 수정
         */
        patch: operations["updateCamera"];
        trace?: never;
    };
    "/api/v1/webrtc/turn-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TURN 자격증명 발급
         * @description 로그인한 사용자 기준으로 TTL이 있는 임시 TURN 계정을 발급합니다. 하드코딩 대신 이 API를 호출하세요.
         */
        get: operations["getTurnCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 보고서 목록 조회 API
         * @description 달력 뷰용 보고서 목록 (최신순)
         */
        get: operations["getReportList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 녹화/캡처 목록 조회 */
        get: operations["getList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 파일 다운로드/스트리밍 */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로필 조회 API
         * @description 사용자의 계정, 반려동물, 기기 설정 정보를 조회합니다.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispensers/logs/watering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 급수 로그 조회 API
         * @description 기간별 급수 로그 조회 (GPT 보고서용)
         */
        get: operations["getWateringLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispensers/logs/feeding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 급식 로그 조회 API
         * @description 기간별 급식 로그 조회 (GPT 보고서용)
         */
        get: operations["getFeedingLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 활동 기록 기간 조회 */
        get: operations["getActivityLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 보고서 삭제 API
         * @description 특정 보고서를 삭제합니다.
         */
        delete: operations["deleteReport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 파일 삭제 */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 계정 삭제 API
         * @description 현재 로그인된 계정과 모든 연관 데이터를 삭제합니다.
         */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseReportDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ReportDTO"];
        };
        FeedingLogSummary: {
            feedTime?: string;
            /** Format: int32 */
            amount?: number;
            /** Format: int32 */
            leftovers?: number;
        };
        FeedingSummaryDTO: {
            /** Format: int32 */
            totalAmount?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            leftovers?: number;
            logs?: components["schemas"]["FeedingLogSummary"][];
        };
        ReportDTO: {
            /** Format: int64 */
            reportId?: number;
            /** Format: date */
            reportDate?: string;
            aiSummary?: string;
            memo?: string;
            feeding?: components["schemas"]["FeedingSummaryDTO"];
            watering?: components["schemas"]["WateringSummaryDTO"];
        };
        WateringLogSummary: {
            wateringTime?: string;
            /** Format: int32 */
            amount?: number;
            /** Format: int32 */
            leftovers?: number;
        };
        WateringSummaryDTO: {
            /** Format: int32 */
            totalAmount?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            leftovers?: number;
            logs?: components["schemas"]["WateringLogSummary"][];
        };
        ApiResponseUploadResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["UploadResultDTO"];
        };
        UploadResultDTO: {
            /** Format: int64 */
            id?: number;
            originalFileName?: string;
            /** @enum {string} */
            type?: "VIDEO" | "IMAGE";
            /** Format: int64 */
            fileSize?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        DeviceSettingDTO: {
            cameraCode: string;
            dispenserCode?: string;
        };
        PetSettingDTO: {
            name: string;
            /** @enum {string} */
            species: "CAT" | "DOG" | "ETC";
            /** @enum {string} */
            gender: "MALE" | "FEMALE";
            /** Format: int32 */
            age?: number;
            /** Format: double */
            weight?: number;
            /** Format: date */
            birthday: string;
        };
        SignUpDTO: {
            email: string;
            password: string;
            nickname: string;
            device?: components["schemas"]["DeviceSettingDTO"];
            pet?: components["schemas"]["PetSettingDTO"];
        };
        ApiResponseSignUpResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SignUpResultDTO"];
        };
        SignUpResultDTO: {
            /** Format: int64 */
            memberId?: number;
            email?: string;
            nickname?: string;
        };
        ApiResponseRefreshResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["RefreshResultDTO"];
        };
        RefreshResultDTO: {
            accessToken?: string;
        };
        VerifyCodeDTO: {
            email: string;
            code: string;
        };
        ApiResponseString: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: string;
        };
        SendCodeDTO: {
            email: string;
        };
        LoginDTO: {
            email: string;
            password: string;
        };
        ApiResponseLoginResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["LoginResultDTO"];
        };
        LoginResultDTO: {
            /** Format: int64 */
            memberId?: number;
            accessToken?: string;
        };
        CreateWateringLogDTO: {
            /** Format: date-time */
            wateringTime: string;
            /** Format: int32 */
            amount: number;
            /** Format: int32 */
            leftovers: number;
        };
        ApiResponseWateringLogDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["WateringLogDTO"];
        };
        WateringLogDTO: {
            /** Format: int64 */
            logId?: number;
            wateringTime?: string;
            /** Format: int32 */
            amount?: number;
            /** Format: int32 */
            leftovers?: number;
            logType?: string;
        };
        CreateFeedingLogDTO: {
            /** Format: date-time */
            feedTime: string;
            /** Format: int32 */
            amount: number;
            /** Format: int32 */
            leftovers: number;
        };
        ApiResponseFeedingLogDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedingLogDTO"];
        };
        FeedingLogDTO: {
            /** Format: int64 */
            logId?: number;
            feedTime?: string;
            /** Format: int32 */
            amount?: number;
            /** Format: int32 */
            leftovers?: number;
            /** Format: int32 */
            consumedAmount?: number;
            logType?: string;
        };
        CreateScheduleDTO: {
            feedTime: string;
            /** Format: int32 */
            amount: number;
        };
        ApiResponseScheduleDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ScheduleDTO"];
        };
        ScheduleDTO: {
            /** Format: int64 */
            scheduleId?: number;
            feedTime?: string;
            /** Format: int32 */
            amount?: number;
        };
        UpdateMemoDTO: {
            memo?: string;
        };
        UpdatePetDTO: {
            name?: string;
            /** @enum {string} */
            species?: "CAT" | "DOG" | "ETC";
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /** Format: int32 */
            age?: number;
            /** Format: double */
            weight?: number;
            /** Format: date */
            birthday?: string;
        };
        ApiResponsePetDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["PetDTO"];
        };
        PetDTO: {
            /** Format: int64 */
            petId?: number;
            name?: string;
            /** @enum {string} */
            species?: "CAT" | "DOG" | "ETC";
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /** Format: int32 */
            age?: number;
            /** Format: double */
            weight?: number;
            /** Format: date */
            birthday?: string;
        };
        UpdateDispenserDTO: {
            deviceName?: string;
            isAutoFeed?: boolean;
            isAutoWater?: boolean;
            /** Format: int32 */
            minWater?: number;
            /** Format: int32 */
            maxWater?: number;
            isCleaningMode?: boolean;
        };
        ApiResponseDispenserDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["DispenserDTO"];
        };
        DispenserDTO: {
            /** Format: int64 */
            dispenserId?: number;
            deviceCode?: string;
            deviceName?: string;
            food?: components["schemas"]["FoodDTO"];
            water?: components["schemas"]["WaterDTO"];
            isCleaningMode?: boolean;
            feedingSchedules?: components["schemas"]["ScheduleDTO"][];
        };
        FoodDTO: {
            isAutoFeed?: boolean;
            latestFeedTime?: string;
            /** Format: int32 */
            leftovers?: number;
        };
        WaterDTO: {
            isAutoWater?: boolean;
            /** Format: int32 */
            minWater?: number;
            /** Format: int32 */
            maxWater?: number;
            latestWateringTime?: string;
            /** Format: int32 */
            leftovers?: number;
        };
        UpdateScheduleDTO: {
            feedTime?: string;
            /** Format: int32 */
            amount?: number;
        };
        UpdateCameraDTO: {
            deviceName?: string;
            /** @enum {string} */
            nightVision?: "AUTO" | "ON" | "OFF";
            isPrivateMode?: boolean;
            isAutoRecordMode?: boolean;
        };
        ApiResponseCameraDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CameraDTO"];
        };
        CameraDTO: {
            /** Format: int64 */
            cameraId?: number;
            deviceCode?: string;
            deviceName?: string;
            /** @enum {string} */
            nightVision?: "AUTO" | "ON" | "OFF";
            isPrivateMode?: boolean;
            isAutoRecordMode?: boolean;
        };
        ApiResponseTurnCredentialResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["TurnCredentialResponse"];
        };
        TurnCredentialResponse: {
            iceServers?: {
                [key: string]: Record<string, never>;
            }[];
            /** Format: int64 */
            expiresAt?: number;
        };
        ApiResponseListReportListDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ReportListDTO"][];
        };
        ReportListDTO: {
            /** Format: int64 */
            reportId?: number;
            /** Format: date */
            reportDate?: string;
            aiSummary?: string;
        };
        ApiResponseRecordingListDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["RecordingListDTO"];
        };
        RecordingItemDTO: {
            /** Format: int64 */
            id?: number;
            originalFileName?: string;
            /** @enum {string} */
            type?: "VIDEO" | "IMAGE";
            /** Format: int64 */
            fileSize?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        RecordingListDTO: {
            recordings?: components["schemas"]["RecordingItemDTO"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        ApiResponseProfileDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ProfileDTO"];
        };
        DeviceProfileDTO: {
            cameraCode?: string;
            isPrivateMode?: boolean;
            isAutoRecordMode?: boolean;
            nightVision?: string;
        };
        PetProfileDTO: {
            name?: string;
            species?: string;
            birthday?: string;
            /** Format: int32 */
            age?: number;
            /** Format: double */
            weight?: number;
            gender?: string;
        };
        ProfileDTO: {
            nickname?: string;
            email?: string;
            pet?: components["schemas"]["PetProfileDTO"];
            device?: components["schemas"]["DeviceProfileDTO"];
        };
        ApiResponseListWateringLogDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["WateringLogDTO"][];
        };
        ApiResponseListFeedingLogDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedingLogDTO"][];
        };
        ActivityLogDTO: {
            /** Format: int64 */
            activityId?: number;
            cameraSessionId?: string;
            /** Format: date-time */
            cameraStartedAt?: string;
            /** Format: date-time */
            detectedStartedAt?: string;
            /** Format: date-time */
            lastDetectedAt?: string;
            /** Format: date-time */
            detectedEndedAt?: string;
            /** Format: int64 */
            detectedSeconds?: number;
            detecting?: boolean;
        };
        ApiResponseListActivityLogDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ActivityLogDTO"][];
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getReport: {
        parameters: {
            query?: {
                reportDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReportDTO"];
                };
            };
        };
    };
    generateReport: {
        parameters: {
            query?: {
                reportDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReportDTO"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query: {
                type: "VIDEO" | "IMAGE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUploadResultDTO"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSignUpResultDTO"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRefreshResultDTO"];
                };
            };
        };
    };
    checkCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCodeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResultDTO"];
                };
            };
        };
    };
    createWateringLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWateringLogDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWateringLogDTO"];
                };
            };
        };
    };
    createFeedingLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedingLogDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedingLogDTO"];
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseScheduleDTO"];
                };
            };
        };
    };
    updateMemo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReportDTO"];
                };
            };
        };
    };
    getMyPet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePetDTO"];
                };
            };
        };
    };
    deletePet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    updatePet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePetDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePetDTO"];
                };
            };
        };
    };
    getMyDispenser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDispenserDTO"];
                };
            };
        };
    };
    deleteDispenser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    updateDispenser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDispenserDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDispenserDTO"];
                };
            };
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseScheduleDTO"];
                };
            };
        };
    };
    getMyCamera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCameraDTO"];
                };
            };
        };
    };
    deleteCamera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    updateCamera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCameraDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCameraDTO"];
                };
            };
        };
    };
    getTurnCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTurnCredentialResponse"];
                };
            };
        };
    };
    getReportList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListReportListDTO"];
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRecordingListDTO"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileDTO"];
                };
            };
        };
    };
    getWateringLogs: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListWateringLogDTO"];
                };
            };
        };
    };
    getFeedingLogs: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFeedingLogDTO"];
                };
            };
        };
    };
    getActivityLogs: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListActivityLogDTO"];
                };
            };
        };
    };
    deleteReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
